In [44]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [47]:
df = pd.read_csv('../eval.csv')
#df.groupby('experiment')['reward'].sum().plot()
df

,action,action_result,distance_to_goal,experiment,gamma,loss,orientation,reward,signal1,signal2,signal3,speed,time
0,-12,MOVE,366.270392,NaN,0.96,0.025473,0.147199,-0.3,0.0000,0.0000,0.0000,4,1
1,-12,FORWARD,362.404087,NaN,0.96,0.110466,0.082083,0.2,0.0000,0.0000,0.0000,4,2
2,3,FORWARD,358.409397,NaN,0.96,0.070984,0.016312,0.2,0.0000,0.0000,0.0000,4,3
3,-12,FORWARD,354.431328,NaN,0.96,0.082790,0.033161,0.2,0.0000,0.0000,0.0000,4,4
4,10,FORWARD,350.453223,NaN,0.96,0.118628,-0.033132,0.2,0.0000,0.0000,0.0000,4,5
5,-12,FORWARD,346.462923,NaN,0.96,0.077699,0.022046,0.2,0.0000,0.0000,0.0000,4,6
6,10,FORWARD,342.502166,NaN,0.96,0.216485,-0.044367,0.2,0.0000,0.0000,0.0000,4,7
7,-17,FORWARD,338.504441,NaN,0.96,0.075020,0.010673,0.2,0.0000,0.0000,0.0000,4,8
8,19,FORWARD,334.643368,NaN,0.96,0.056035,-0.083646,0.2,0.0000,0.0000,0.0000,4,9
9,-12,FORWARD,330.652110,NaN,0.96,0.031109,0.020921,0.2,0.0000,0.0000,0.0108,4,10
10,12,FORWARD,326.693388,NaN,0.96,0.056757,-0.045492,0.2,0.0000,0.0000,0.0372,4,11
11,12,FORWARD,322.701881,NaN,0.96,0.147171,0.020619,0.2,0.0000,0.0000,0.0372,4,12
12,12,FORWARD,318.854052,NaN,0.96,0.064176,0.087541,0.2,0.0000,0.0000,0.0248,4,13
13,12,FORWARD,315.326284,NaN,0.96,0.025877,0.155292,0.2,0.0000,0.0000,0.0000,4,14
14,-12,FORWARD,312.286023,NaN,0.96,0.072526,0.223852,0.2,0.0000,0.0000,0.0124,4,15
15,12,FORWARD,308.785719,NaN,0.96,0.105660,0.159822,0.2,0.0000,0.0000,0.0000,4,16
16,-12,FORWARD,305.783936,NaN,0.96,0.036868,0.228473,0.2,0.0000,0.0000,0.0000,4,17
17,-12,FORWARD,302.313044,NaN,0.96,0.157113,0.164545,0.2,0.0000,0.0000,0.0160,4,18
18,12,FORWARD,298.511218,NaN,0.96,0.118339,0.099960,0.2,0.0000,0.0000,0.0060,4,19
19,-12,FORWARD,295.062043,NaN,0.96,0.096516,0.167944,0.2,0.0000,0.0000,0.0096,4,20
20,12,FORWARD,291.274236,NaN,0.96,0.037729,0.103450,0.2,0.0000,0.0000,0.0028,4,21
21,-12,FORWARD,287.848299,NaN,0.96,0.026385,0.171512,0.2,0.0000,0.0000,0.0060,4,22
22,-12,FORWARD,284.075721,NaN,0.96,0.078350,0.107115,0.2,0.0000,0.0000,0.0040,4,23
23,10,FORWARD,280.110866,NaN,0.96,0.081275,0.041929,0.2,0.0000,0.0000,0.0000,4,24
24,-12,FORWARD,276.301921,NaN,0.96,0.153805,0.098081,0.2,0.0000,0.0000,0.0000,4,25
25,-12,FORWARD,272.323465,NaN,0.96,0.084060,0.032812,0.2,0.0000,0.0000,0.0000,4,26
26,10,FORWARD,268.345757,NaN,0.96,0.066305,-0.033373,0.2,0.0000,0.0000,0.0000,4,27
27,-12,FORWARD,264.355176,NaN,0.96,0.034374,0.021686,0.2,0.0000,0.0000,0.0000,4,28
28,10,FORWARD,260.395070,NaN,0.96,0.073515,-0.044653,0.2,0.0000,0.0000,0.0000,4,29
29,-12,FORWARD,256.397163,NaN,0.96,0.060441,0.010219,0.2,0.0000,0.0000,0.0000,4,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29414,-9,FORWARD,299.634735,NaN,0.96,0.021147,-0.098689,0.2,0.0000,0.0000,0.0000,4,38
29415,19,FORWARD,296.076194,NaN,0.96,0.077473,-0.149985,0.2,0.0000,0.0000,0.0000,4,39
29416,-9,FORWARD,292.119161,NaN,0.96,0.145446,-0.046382,0.2,0.0000,0.0000,0.0000,4,40
29417,-9,FORWARD,288.306009,NaN,0.96,0.062753,-0.097015,0.2,0.0000,0.0036,0.0000,4,41
29418,-9,FORWARD,284.738235,NaN,0.96,0.072418,-0.148340,0.2,0.0000,0.0056,0.0000,4,42
29419,19,FORWARD,281.514598,NaN,0.96,0.007501,-0.200349,0.2,0.0000,0.0240,0.0000,4,43
29420,-9,FORWARD,277.703233,NaN,0.96,0.063780,-0.097456,0.2,0.0092,0.0400,0.0000,4,44
29421,-9,FORWARD,274.138532,NaN,0.96,0.065023,-0.148838,0.2,0.0000,0.0500,0.0000,4,45
29422,-9,FORWARD,270.919645,NaN,0.96,0.032257,-0.200932,0.2,0.0000,0.0580,0.0000,4,46
29423,-15,FORWARD,268.139599,NaN,0.96,0.072857,-0.253705,0.2,0.0000,0.0232,0.0000,4,47
29424,5,FORWARD,266.240488,NaN,0.96,0.022227,-0.340435,0.2,0.0000,0.0232,0.0000,4,48
29425,19,FORWARD,264.085204,NaN,0.96,0.105113,-0.316851,0.2,0.0000,0.0464,0.0000,4,49
29426,-9,FORWARD,260.978180,NaN,0.96,0.118938,-0.215341,0.2,0.0000,0.0464,0.0000,4,50
29427,-15,FORWARD,258.335113,NaN,0.96,0.083916,-0.268396,0.2,0.0000,0.0232,0.0000,4,51
29428,19,FORWARD,256.605154,NaN,0.96,0.065080,-0.355410,0.2,0.0000,0.0416,0.0000,4,52
29429,-9,FORWARD,253.831494,NaN,0.96,0.021446,-0.254313,0.2,0.0432,0.0576,0.0200,4,53
29430,-19,FORWARD,251.583019,NaN,0.96,0.097160,-0.307908,0.2,0.0728,0.0864,0.0352,4,54
29431,-19,FORWARD,250.589279,NaN,0.96,0.066585,-0.417630,0.2,0.0792,0.1188,0.0380,4,55
29432,-19,MOVE,250.973538,NaN,0.96,0.095730,-0.528098,-0.3,0.0612,0.1092,0.0256,4,56
29433,-19,MOVE,252.687959,NaN,0.96,0.087927,-0.638707,-0.3,0.0416,0.0780,0.0156,4,57
29434,19,MOVE,255.521745,NaN,0.96,0.077041,-0.748831,-0.3,0.0708,0.0896,0.0476,4,58
29435,19,MOVE,257.326848,NaN,0.96,0.013174,-0.646811,-0.3,0.0996,0.0988,0.0820,4,59
29436,19,MOVE,257.929382,NaN,0.96,0.075612,-0.545687,-0.3,0.1204,0.1232,0.1160,4,60
29437,19,FORWARD,257.272058,NaN,0.96,0.071074,-0.445017,0.2,0.1436,0.1600,0.1444,4,61
29438,19,FORWARD,255.417392,NaN,0.96,0.020928,-0.344337,0.2,0.1808,0.2008,0.1900,4,62
29439,19,FORWARD,252.544201,NaN,0.96,0.079127,-0.243182,0.2,0.2448,0.2396,0.2116,4,63
29440,19,FORWARD,248.936792,NaN,0.96,0.167963,-0.141115,0.2,0.2920,0.2720,0.2864,4,64
29441,19,FORWARD,244.965351,NaN,0.96,0.035714,-0.037753,0.2,0.3312,0.2980,0.3424,4,65
29442,19,FORWARD,241.055583,NaN,0.96,0.032682,0.067187,0.2,0.3172,0.2700,0.3492,4,66
29443,19,HIT_TREE,237.646573,NaN,0.96,0.167318,0.173850,-1.0,0.2968,0.2484,0.3228,4,67

In [48]:
df.groupby('action_result').count()

,action,distance_to_goal,experiment,gamma,loss,orientation,reward,signal1,signal2,signal3,speed,time
action_result,,,,,,,,,,,,
FORWARD,22642,22642,0,22642,22642,22642,22642,22642,22642,22642,22642,22642
GOAL,8,8,0,8,8,8,8,8,8,8,8,8
HIT_TREE,292,292,0,292,292,292,292,292,292,292,292,292
MOVE,6451,6451,0,6451,6451,6451,6451,6451,6451,6451,6451,6451
ON_EDGE,51,51,0,51,51,51,51,51,51,51,51,51

In [38]:
df = pd.read_csv('../eval.csv')
df.groupby('action_result').count()

,action,distance_to_goal,experiment,gamma,loss,orientation,reward,signal1,signal2,signal3,speed,time
action_result,,,,,,,,,,,,
FORWARD,13915,13915,13915,13915,9196,13915,13915,13915,13915,13915,13915,13915
GOAL,18,18,18,18,18,18,18,18,18,18,18,18
HIT_TREE,279,279,279,279,253,279,279,279,279,279,279,279
MOVE,7426,7426,7426,7426,2692,7426,7426,7426,7426,7426,7426,7426
ON_EDGE,27,27,27,27,26,27,27,27,27,27,27,27